version: '3.8'

services:
  api:
    ports:
      - "5000:5000"
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    volumes:
      - ./api:/app
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 5000 --reload
    networks:
      - esp-ai-network

networks:
  esp-ai-network:
    external: true