CREATE TYPE task_type AS ENUM (
	'ALARM',
	'WAKE_UP_AI',
    'CHANGE_VOLUME'

);

CREATE TYPE task_status AS ENUM (
	'PENDING',
	'IN_PROGRESS',
	'COMPLETED',
	'CANCELED'
);

CREATE TABLE IF NOT EXISTS "TASKS" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "device" VARCHAR(31) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "run_at" TIMESTAMPTZ NOT NULL,
    "type" task_type NOT NULL,
    "status" task_status NOT NULL,
    "argument" VARCHAR(255),
    PRIMARY KEY ("id")
);

CREATE TYPE "role" AS ENUM (
	'user',
	'system',
	'assistant',
	'tool'
);

CREATE TYPE "context_type" AS ENUM (
	'system',
	'summary',
	'sub_system'
);

CREATE TABLE IF NOT EXISTS "SYSTEMS" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"type" "context_type" NOT NULL,
	"content" VARCHAR(5000) NOT NULL,
	"device" VARCHAR(31),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "MESSAGES" (
	"id" SERIAL NOT NULL,
	"content" VARCHAR(5000) NOT NULL,
	"role" "role" NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"system" INTEGER NOT NULL,
	"device" VARCHAR(31),
	PRIMARY KEY("id"),

    FOREIGN KEY ("system")
        REFERENCES "SYSTEMS"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE
);