CREATE TYPE task_type AS ENUM (
	'ALARM',
	'WAKE_UP_AI',
    'CHANGE_VOLUME'

);

CREATE TYPE task_status AS ENUM (
	'PENDING',
	'IN_PROGRESS',
	'COMPLETED',
	'CANCELED'
);

CREATE TABLE IF NOT EXISTS "TASKS" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "device" VARCHAR(31) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "run_at" TIMESTAMPTZ NOT NULL,
    "type" task_type NOT NULL,
    "status" task_status NOT NULL,
    "argument" VARCHAR(255),
    PRIMARY KEY ("id")
);