CREATE TYPE task_type AS ENUM (
	'ALARM',
	'MSG_FROM_AI'
);

CREATE TYPE task_status AS ENUM (
	'PENDING',
	'IN_PROGRESS',
	'COMPLETED',
	'CANCELED'
);

CREATE TABLE IF NOT EXISTS "TASKS" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "run_at" TIMESTAMPTZ NOT NULL,
    "type" task_type NOT NULL,
    "status" task_status NOT NULL,
    "argument" VARCHAR(255),
    PRIMARY KEY ("id")